NOISE_STD_MCMC: 0.5
METR_STEPS: 1000
RANDOM_STATE: 13
n_epochs: 20000
n_samples_y: 100
n_samples_x: 30000
batch_size: 1000
resume_training: False
model: 'CDiffE'
loss_fn: 'DSM_PDE'
lam: 0.01
pde_loss: 'FPE'
pde_metric: 'L2'
train_dir: 'test'
out_dir: 'test'
lr: 0.0001
hidden_layers: [512,512,512]
plot_ys: [0,5,6,20,23,42,50,77,81,93]
