n_samples_y: 100
n_samples_x: 30000
dataset_size: 100000
lr: 0.0001
lr_INN: 0.001
train_size: .9
random_state: 7
n_epochs_dsm: 5
n_epochs_SNF: 10
n_epochs_INN: 5
train_dir: 'trained_models/linearModel/baselines'
out_dir: 'results/linearModel/baselines'
model: 'CDE'
num_layers_INN: 4
size_hidden_layers_INN: 64
metr_steps_per_block: 10
noise_std: 0.4
batch_size: 1000
hidden_layers: [512,512,512]
