lr: 0.0001
hidden_layers: [512,512,512]
resume_training: False
n_epochs: 20000
n_samples_y: 100
n_samples_x: 30000
batch_size: 1000
src_dir: 'grid_search_results/scatterometry'
plot_ys: [0,5,6,20,23,42,50,77,81,93]
params: {'loss_fn': ['PINNLoss', 'DSM_PDE'],
              'lam': [1.,0.1,0.01,.001,0001],
              'lam2': [1.,0.01,.001,.0001],
              'pde_loss': ['FPE', 'cScoreFPE'],
              'pde_metric': ['L1','L2'],
              'model': ['CDE'],
              'ic_metric': ['L1','L2']}
             

