n_samples_y: 100
n_samples_x: 30000
dataset_size: 100000
lr: 0.0001
lr_INN: 0.001
NOISE_STD_MCMC: 0.5
METR_STEPS: 1000
RANDOM_STATE: 13
n_epochs_dsm: 20000
n_epochs_SNF: 2500
n_epochs_INN: 2500
plot_ys: [0,5,6,20,23,42,50,77,81,93]
train_dir: 'trained_models/scatterometry/baselines'
out_dir: 'results/scatterometry/baselines'
model: 'CDE'
num_layers_INN: 4
size_hidden_layers_INN: 64
metr_steps_per_block: 10
noise_std: 0.4
batch_size: 1000
hidden_layers: [512,512,512]
